import React,{createContext,useContext,useEffect,useState} from 'react';
import api from '../services/api';
const AuthContext=createContext(null);
export const AuthProvider=({children})=>{const[user,setUser]=useState(null);const[loading,setLoading]=useState(true);
 const checkAuthStatus=async()=>{try{const r=await api.get('/auth/me');setUser(r.data.user)}catch{setUser(null)}finally{setLoading(false)}};useEffect(()=>{checkAuthStatus()},[]);
 const login=async(email,password)=>{try{const r=await api.post('/auth/login',{email,password});setUser(r.data.user);return r.data.user}catch(e){throw new Error(e.response?.data?.error||'Failed to login.')}};
 const register=async(payload)=>{try{const r=await api.post('/auth/register',payload);setUser(r.data.user);return r.data.user}catch(e){throw new Error(e.response?.data?.error||'Registration failed.')}};
 const logout=async()=>{try{await api.post('/auth/logout')}finally{setUser(null)}};
 return <AuthContext.Provider value={{user,loading,login,register,logout,checkAuth:checkAuthStatus}}>{children}</AuthContext.Provider>};
export const useAuth=()=>useContext(AuthContext);
