import React,{useState} from 'react'; import {Link,useNavigate} from 'react-router-dom'; import {useAuth} from '../context/AuthContext'; import Input from '../components/Input'; import Button from '../components/Button'; import ErrorMessage from '../components/ErrorMessage';
const Register=()=>{const nav=useNavigate();const{register}=useAuth();const [form,setForm]=useState({name:'',email:'',password:'',confirmPassword:'',relationship:'Myself',patientName:'',age:'',gender:'',bloodGroup:'',phone:'',address:''});const[error,setError]=useState('');const[loading,setLoading]=useState(false);const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const submit=async e=>{e.preventDefault();setError('');if(form.password!==form.confirmPassword)return setError('Passwords do not match.');setLoading(true);try{await register({...form});nav('/dashboard')}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <div className="auth-container"><div className="auth-card"><div className="auth-header"><span className="auth-logo">🛡️</span><h2>Create Account</h2><p>Create your account and patient profile</p></div><ErrorMessage message={error} onClose={()=>setError('')}/><form onSubmit={submit} className="auth-form">
 <Input label="Account Holder Name" id="name" value={form.name} onChange={e=>set('name',e.target.value)} required autoComplete="name"/><Input label="Email Address" id="email" type="email" value={form.email} onChange={e=>set('email',e.target.value)} required autoComplete="email"/>
 <label className="input-label" htmlFor="relationship">Relationship to Patient</label><select id="relationship" className="input-field" value={form.relationship} onChange={e=>set('relationship',e.target.value)}><option>Myself</option><option>Child</option><option>Parent</option><option>Sibling</option><option>Spouse</option><option>Other</option></select>
 <h3 className="form-section-title">Patient Information</h3><Input label="Patient Full Name" id="patientName" value={form.patientName} onChange={e=>set('patientName',e.target.value)} required/><Input label="Age" id="age" type="number" min="0" max="130" value={form.age} onChange={e=>set('age',e.target.value)} required/>
 <label className="input-label" htmlFor="gender">Gender</label><select id="gender" className="input-field" value={form.gender} onChange={e=>set('gender',e.target.value)} required><option value="">Select gender</option><option>Male</option><option>Female</option><option>Other</option></select>
 <label className="input-label" htmlFor="bloodGroup">Blood Group</label><select id="bloodGroup" className="input-field" value={form.bloodGroup} onChange={e=>set('bloodGroup',e.target.value)} required><option value="">Select blood group</option>{['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(x=><option key={x}>{x}</option>)}</select>
 <Input label="Phone Number" id="phone" value={form.phone} onChange={e=>set('phone',e.target.value)} required/><label className="input-label" htmlFor="address">Address</label><textarea id="address" className="input-field" value={form.address} onChange={e=>set('address',e.target.value)} required rows="3"/>
 <Input label="Password" id="password" type="password" value={form.password} onChange={e=>set('password',e.target.value)} required autoComplete="new-password"/><Input label="Confirm Password" id="confirmPassword" type="password" value={form.confirmPassword} onChange={e=>set('confirmPassword',e.target.value)} required autoComplete="new-password"/>
 <Button type="submit" variant="primary" loading={loading} className="w-full">Register Account</Button></form><div className="auth-footer"><p>Already have an account? <Link to="/login">Log in here</Link></p></div></div></div>}; export default Register;
